version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestControls_3Project
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: testAssetsOnPrem_2
  version: "1.0"
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: DesignerStepsInCloudEditorTxPipelinePackage
  version: "1.0"
  gitServerName: test
  gitUrl: https://github.com/santhu736852
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: DesignerStepsInCloudEditorPackageWithoutRepeat
  version: "1.0"
  gitServerName: test
  gitUrl: https://github.com/santhu736852
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testcontrols_3.integrations:repeat_control
  packages:
  - name: TestControls_3Project
    version: "1.0"
  - name: DesignerStepsInCloudEditorTxPipelinePackage
    version: "1.0"
  - name: testAssetsOnPrem_2
    version: "1.0"
  - name: DesignerStepsInCloudEditorPackageWithoutRepeat
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
